config/routes.rb
Railsdev::Application.routes.draw do
  resources :attachments

  resources :posts do
    collection do
      get 'add_attachment'
    end
  end
  
  

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users, :controllers => { :registrations => "registrations", :confirmations => "confirmations" }
  resources :users do
      get 'list', :on => :collection
      get 'invite', :on => :member
  end
get 'home/index' => 'home#index', :as => :home_index  
get 'home/about' => 'home#about', :as => :about
get 'home/projects' => 'home#projects', :as => :projects
get 'home/contact' => 'home#contact', :as => :contact
post 'home/make_contact' => 'home#make_contact', :as => :make_contact
get 'home/blog' => 'home#blog', :as => :blog

get 'mobile/posts' => 'mobile#posts', :as => :mobile_posts
get 'mobile/home' => 'mobile#home', :as => :mobile_root
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
  # override Devise method
  # no password is required when the account is created; validate password when the user sets one
  validates_confirmation_of :password
  def password_required?
    if !persisted? 
      !(password != "")
    else
      !password.nil? || !password_confirmation.nil?
    end
  end
  
  # override Devise method
  def confirmation_required?
    false
  end
  
  # override Devise method
#  def active_for_authentication?
#    confirmed? || confirmation_period_valid?
#  end
  
  # new function to set the password
  def attempt_set_password(params)
    p = {}
    p[:password] = params[:password]
    p[:password_confirmation] = params[:password_confirmation]
    update_attributes(p)
  end
  
  # new function to determine whether a password has been set
  def has_no_password?
    self.encrypted_password.blank?
  end

  # new function to provide access to protected method pending_any_confirmation
  def only_if_unconfirmed
    pending_any_confirmation {yield}
  end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def list
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
  end
  
  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.paginate(:page => params[:page], :per_page => 5)   
  end

  def show
    @user = User.find(params[:id])
  end
  
  def invite
    authorize! :invite, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    @user.send_confirmation_instructions
    redirect_to :back, :only_path => true, :notice => "Sent invitation to #{@user.email}."
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline' %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<div id="top-container" class="covering-main-page">
	<div id="global-header">
        <div class="global-bar">
             <nav role="navigation">                 
                 <h1 class="logo">
                     <a href="/"><img src="/assets/RORD_logo.png" width="350" height="30" data-retina /></a>
                 </h1>                 
                 <ul id="global-navigation" class="main" role="navigation">
				  <% if user_signed_in? %>
					<li><%= link_to current_user.email, edit_user_registration_path, :class => 'active' %></li>
					<li><%= link_to 'Projects', projects_path %></li>
					<li><%= link_to 'About', about_path %></li>
					<li><%= link_to 'Experience', posts_path %></li>
				  <% else %>
					<li><%= link_to 'More Info', new_user_registration_path %></li>
					<li><%= link_to 'Login', new_user_session_path %></li>
				  <% end %>	
                 </ul>                
             </nav>
         </div>
     </div>	
</div>

<div id="container">
	
	<div class="main-page">
				
		<div id="showcase-content" class="include-shadow" style='height:600px;'>
			<div id="app-rdio" class="showcase columns active" style="left: 0;">
				<div class="cell width-12 first">
					
					<hgroup>
						<h3>Admin</h3>
						<%= link_to 'Logout', destroy_user_session_path, :method=>'delete', :class => 'btn' %>
					</hgroup>
				</div>
				
<div class="cell width-12 first">	
	<div class="rich-content">


<h3>Roles and Stats</h3>
<table class="table table-condensed">
	  <thead>
      <tr>
          <th>Username</th>
          <th>Email</th>
          <th>Registered</th>
		  <th>Confirmed</th>
          <th>Role</th>
		  <th>Visits</th>
          <th></th>
          <th></th>
          <th></th>                            
      </tr>
  </thead>   
  <tbody>
  <% @users.each do |user| %>
    <tr>
        <td><%= link_to user.name, user %></td>
        <td><%= user.email %></td>
        <td><%= user.created_at.to_date %></td>
		<td><%= user.confirmed_at.to_date if user.confirmed_at %></td>
        <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
        <td><%= user.sign_in_count if user.sign_in_count %></td>
		<td><%= (user.confirmation_token.nil? ? (link_to "send invitation", invite_user_path(user)) : (link_to "resend", invite_user_path(user))) unless user.confirmed_at %></td>
        <td>
          <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change role</a>
        </td>
        <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>                                       
    </tr>
  <% end %>
  </tbody>
</table>
<%= will_paginate @users, :class => 'pagination pagination-right pagination-small'%>

	</div>

</div>
<hr />
	
</div>
</div>
</div>
</div>

<!-- Modal -->
<% @users.each do |user| %>
<%= render user %>
<% end %>

app/views/users/list.html.erb
<div id="top-container" class="covering-main-page">
	<div id="global-header">
        <div class="global-bar">
             <nav role="navigation">                 
                 <h1 class="logo">
                     <a href="/"><img src="/assets/RORD_logo.png" width="350" height="30" data-retina /></a>
                 </h1>                 
                 <ul id="global-navigation" class="main" role="navigation">
				  <% if user_signed_in? %>
					<li><%= link_to current_user.email, edit_user_registration_path %></li>
					<li><%= link_to 'Projects', projects_path, :class => 'active' %></li>
					<li><%= link_to 'About', about_path %></li>
					<li><%= link_to 'Experience', posts_path %></li>
				  <% else %>
					<li><%= link_to 'More Info', new_user_registration_path %></li>
					<li><%= link_to 'Login', new_user_session_path %></li>
				  <% end %>	
                 </ul>                
             </nav>
         </div>
     </div>	

</div>


	<div id="container">
	
	<div class="main-page">
				
		<div id="showcase-content" class="include-shadow"  style='height:2300px;'>
			<div id="home_page" class="showcase columns active" style="left: 0;">
				<div class="cell width-12 first">


<% require 'mem_info' %>
<% m = MemInfo.new %>
<% vars = m.instance_variables %>
<div class='row'>
  <div class='span3'>
   <table class='table table-condensed table-bordered table-striped'>
     <% vars.each do |v| %>
        <tr>
                <th style='text-align:left;'><%= v.to_s.gsub!('@','').titleize %>:</th>
                <td style='text-align:right;'><%= number_with_delimiter(m.instance_variable_get(v) )  %></td>
        </tr>
     <% end %>
   </table>
  </div>
</div>
<br><br>
		
<pre>
<%= link_to 'Network Solutions', 'http://www.networksolutions.com' %><br>
www.denenberg.net 
DNS: networksolutions
User ID: 25316411
User Name: Andy Denenberg
git: stin_v3
host: stin_v3.heroku.com

ftv3.heroku.com
ospreypoint.heroku.com
talonv2.heroku.com
www.ospreypointcap.com
www.ospreypointpartners.com
ror.ospreypointpartners.com
stc.ospreypointcap.com
standtall.ospreypointcap.com
</pre>

	
				</div>


			</div>
		</div>			
	</div>
	
			<table class='center_table'><tr><td>
				<div class='center_text'>
				<br><br>	Copyright 2012 Osprey Point, LLC<br /> 
				</div>
				<br></td></tr>
			</table>					        
	
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>