config/routes.rb
Railsdev::Application.routes.draw do
  resources :attachments

  resources :posts do
    collection do
      get 'add_attachment'
    end
  end
  
  

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users, :controllers => { :registrations => "registrations", :confirmations => "confirmations" }
  resources :users do
      get 'list', :on => :collection
      get 'invite', :on => :member
  end
get 'home/index' => 'home#index', :as => :home_index  
get 'home/about' => 'home#about', :as => :about
get 'home/projects' => 'home#projects', :as => :projects
get 'home/contact' => 'home#contact', :as => :contact
post 'home/make_contact' => 'home#make_contact', :as => :make_contact
get 'home/blog' => 'home#blog', :as => :blog

get 'mobile/posts' => 'mobile#posts', :as => :mobile_posts
get 'mobile/home' => 'mobile#home', :as => :mobile_root
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  attr_accessible :body, :category, :title, :user_id, :attachments_attributes
  has_many :attachments, :dependent => :destroy
  accepts_nested_attributes_for :attachments, :allow_destroy => true
  
  
  def next
    post = Post.where("posts.id > ?", self.id).order("posts.id ASC").limit(1)
    post.empty? ? Post.last : post.first
  end

  def previous
    post = Post.where("posts.id < ?", self.id).order("posts.id DESC").limit(1)
    post.empty? ? Post.first : post.first
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!

  def add_attachment
    @post = Post.find(params[:post])
    @post.attachments.new
    render :partial => 'add_attachment', :layout => false    
  end

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @posts = Post.paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  def show
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @post = Post.find(params[:id])
      @user = User.new
      @user.name = ''

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  def new
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @post = Post.new
    @post.attachments.build
    

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  def edit
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @post = Post.find(params[:id])
  end

  def create
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_add_attachment.html.erb
<class ='row'>

<%= simple_form_for(@post, :html => { :class => 'form-vertical span6' } ) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
		<%= f.fields_for :attachments do |attach| %>
		
		  	<% if attach.object.new_record? %>
				<h4>Attachments:</h4>
				<div class='row'>
					<div class='span3'>
							<label for="stackedSelect">URL</label>
							<%= attach.text_field :url , :class => "input span3"%>
							<label for="stackedSelect">Description</label>
					</div>
					<div class='span2'>
							<label for="stackedSelect">File</label>
							<%= attach.file_field :file %>
					</div>
				</div>
			<% end %>
		<% end %>
	
  </div>

  <div class="form-actions">
    <%= f.button :submit , 'Save' %> | 
	<%= link_to 'Cancel', @post %>
  </div>
<% end %>

</div>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>

  <lable>Title</lable><br>
  <%= f.text_field :title %><br>
  <lable>Message</lable><br>
  <%= f.text_area :body, :rows => 7, :class => 'span5' %><br><br>
	<lable>Category</lable><br>
	<%= f.select :category , Category.new.array %><br>
	<lable>User</lable><br>
	<%= f.select :user_id , User.order('name').collect { |u|  [ u.name, u.id ] }, :html => { :selected => current_user.id } %>

	<% i = 0 %>
	<%= f.fields_for :attachments do |attach| %>
	<div class='form-box'>
	<div class='row'>
		<div class='span4'>
			<% if !attach.object.new_record? %>
			<label class="checkbox inline">
		<!--- attach.check_box :_destroy, {:checked => attach.object.persisted?}, '0', '1' %>Save Attachment? ---->
				<%= attach.check_box :_destroy %><b>Delete Attachment <%= i ; i += 1 %></b>					
			</label>
			<% else %>
			<label for="stackedSelect"><b>Attachment</b></label>
			<% end %>				
		</div>
	</div>
	<br>
	<div class='row'>
		<div class='span4'>
				<label for="stackedSelect">URL</label>
				<%= attach.text_field :url , :class => "input span3"%>
				<label for="stackedSelect">Description</label>
		</div>
		<div class='span4'>
				<label for="stackedSelect">Current File: <b><%= attach.object.file_file_name %></b></label><br>
				<%= attach.file_field :file %>
		</div>
	</div>
	</div>
	<% end %>



  <div class="form-actions">
    <%= f.button :submit, :class => 'btn btn-info' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div id="top-container">
	<div id="global-header">
		<div class="local-bar">
			<nav role="navigation">
				
				<h1 class="logo">
					<a href="/"><img src="/assets/RORD_logo.png" width="350" height="30" data-retina /></a>
				</h1>
				
				<ul class="local-navigation main" role="navigation">
					<li><a href="/">Home</a></li>
					<li class="dropdown"><a href="#">Information</a>
						<ul>
							<li><%= link_to 'Projects', projects_path %></li>
							<li><%= link_to 'About', about_path %></li>
							<li><%= link_to 'Contact', '#' %></li>
						</ul>
					</li>
					<li><%= link_to 'Experience', posts_path, :class => "active" %></li>
				</ul>
			</nav>
		</div>
	</div>
	<div class="Head transparent-bar" id="Head">
		<div class="Row">
			<ul class="ForumMenu">
				<li><%= link_to 'Posts', posts_path, :class => "active" %></li>
				<li><a href="#" class="BestOf">Placeholder</a></li>
			</ul>
			<div class="MeBox MeBox-SignIn Inline FlyoutRight">
				<div class="SignInLinks"><a href="#" class="">Post #<%= @post.id %></a> </div>
			</div>
			
		</div>
	</div>
</div>

<div id="Frame">

<div id="container">

<div class="main-page">
			
	<div id="showcase-content" class="include-shadow">
		<div id="app-rdio" class="showcase columns active" style="left: 0;">
			<div class="cell width-12 first">

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

</div>
</div>
</div>
</div>
</div>
</div>
</div>

app/views/posts/index.html.erb
<div id="top-container">
	<div id="global-header">
		<div class="local-bar">
			<nav role="navigation">
				
				<h1 class="logo">
					<a href="/"><img src="/assets/RORD_logo.png" width="350" height="30" data-retina /></a>
				</h1>
				
				<ul class="local-navigation main" role="navigation">
					<li><a href="/">Home</a></li>
					<li class="dropdown"><a href="#">Information</a>
						<ul>
							<li><%= link_to 'Projects', projects_path %></li>
							<li><%= link_to 'About', about_path %></li>
							<li><%= link_to 'Contact', '#' %></li>
						</ul>
					</li>
					<li><a href="#" class="active">Experience</a></li>
					<li><%= link_to current_user.email, edit_user_registration_path %></li>
				</ul>
			</nav>
		</div>
	</div>
	<div class="Head transparent-bar" id="Head">
		<div class="Row">
			<ul class="ForumMenu">
				<li><a href="#" class="">Posts</a></li>
				<li><a href="#" class="BestOf"></a></li>
			</ul>
		</div>
	</div>
</div>

<div id="Frame">
   <div id="Body">
      <div class="Row">

<div class="Column ContentColumn">
	<div class="ForumSearch">
		<form method="get" action="/search">
			<div>
				<input type="text" id="Form_Search" name="Search" value="" placeholder="Search forums..." class="InputBox" /><input type="submit" id="Form_Go" value="Go" class="Button" />
			</div>
		</form>
	</div>
    
	<div class="MessageList Discussion"><!-- Page Title -->
		<div class="PageTitle"><h1>Key Findings</h1>
		</div>



<div class="P PageDescription"></div>
   <div class="DataTableWrap">
   <table class="DataTable CategoryTable">
      <thead>
      <tr>
	      <td>Title</td>
	      <td>Category</td>
	      <td>User</td>
		  <td>Attachments</td>
	      <td>Body</td>
		  <td>Actions</td>
   	  </tr>
      </thead>
      <tbody>
		<% @posts.each do |post| %>
            <tr class="Item Category-ios Depth1 Depth-1 Unread">
      			<td><%= link_to post.title, post_path(post) %></td>
		      <td><%= Category.new.array[post.category][0] %></td>
		      <td><%= User.find(post.user_id).name %></td>
			  <td><%= post.attachments.count %></td>
		      <td><pre><%= post.body[0..20] %></pre></td>
		    <td><%= link_to 'Show', post_path(post) %>
		        <%= link_to 'Edit', edit_post_path(post) %>
		        <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
   		</tr>
<% end %>

         </tbody>
   </table>
	<br>
	<%= will_paginate @users, :class => 'pagination pagination-right pagination-small'%>
	
	<%= link_to 'New Post', new_post_path, :class => 'btn' %>
	

   </div>

  </div>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div id="top-container">
	<div id="global-header">
		<div class="local-bar">
			<nav role="navigation">
				
				<h1 class="logo">
					<a href="/"><img src="/assets/RORD_logo.png" width="350" height="30" data-retina /></a>
				</h1>
				
				<ul class="local-navigation main" role="navigation">
					<li><a href="/">Home</a></li>
					<li class="dropdown"><a href="#">Information</a>
						<ul>
							<li><%= link_to 'Projects', projects_path %></li>
							<li><%= link_to 'About', about_path %></li>
							<li><%= link_to 'Contact', '#' %></li>
						</ul>
					</li>
					<li><%= link_to 'Experience', posts_path, :class => "active" %></li>
				</ul>
			</nav>
		</div>
	</div>
	<div class="Head transparent-bar" id="Head">
		<div class="Row">
			<ul class="ForumMenu">
				<li><%= link_to 'Posts', posts_path, :class => "active" %></li>
				<li><a href="#" class="BestOf">Placeholder</a></li>
			</ul>
			<div class="MeBox MeBox-SignIn Inline FlyoutRight">
				<div class="SignInLinks"><a href="#" class="">Post #<%= @post.id %></a> </div>
			</div>
			
		</div>
	</div>
</div>

<div id="Frame">
   <div id="Body">
      <div class="Row">

            <div class="MessageList Discussion"><!-- Page Title -->
<br>
<div id="container">
	<div class="main-page" id="blog-page">
		<div class="content flush-padding"  style='height:800px;'>
			<div class="columns">
				<div class="cell width-8 first vertical-gap">
					<div class="blog-posts ">

						
<article>
<hgroup>
	<header>
	By: <%= User.find(@post.user_id).name %> - Last Updated: <%= @post.updated_at.strftime("%m/%d/%Y") %><br>
	</header>	
	
	<h2><%= @post.title %></h2>
	
	<footer>
	<%= link_to 'Edit', edit_post_path(@post), :class => 'btn btn-mini' %> |
	<%= link_to 'Back', posts_path, :class => 'btn btn-mini' %> |
	<%= link_to_function 'Add Attachment', "AddAttachment(" + @post.id.to_s + "); return false", :class => 'btn btn-mini btn-primary' %>	
	</footer>
</hgroup>

<div class="entry-content rich-content">
	
	<div id='attachment'></div>

<%= @post.body.html_safe %>

<% if @post.attachments.count > 0 %>
<br><br><b>Attachments:</b><br><br>
<% @post.attachments.each do |attach| %>
	<% if !attach.url.blank? %>
		<code>Link: <%= link_to attach.url, "http://" + attach.url, :target => '_blank' %></code>
	<% end %>
	<% if !attach.file.url.include?('missing.png') %>
	<code>File: <%= link_to attach.file.url, attach.file.url, :target => '_blank' %></code><br>
	<%= image_tag attach.file.url :thumb %>
	<% end %>
	<br>
	<% end %> 
<% end %>
<br>
</div>
</article>

<div class="navigation">
		<div class="nav-previous">
			
			&larr;<%= link_to ' Older Post' , post_path(@post.previous), :class => "meta-nav" %></div>
		<div class="nav-next"><%= link_to ' Newer Post' , post_path(@post.next), :class => "meta-nav" %>&rarr;</div>
	</div>
					</div>
				</div>
				<div class="blog-sidebar cell width-4 append-gutter vertical-gap" >
					<div id="secondary" class="widget-area" role="complementary">
						
<aside class="widget s2_form_widget"><form method="get" action="#">
<%= text_field_tag 'search', "Search" %>
</form>
</aside>

<aside class="widget s2_form_widget"><h3 class="widget-title">Subscribe</h3><div class="search">

	<%= simple_form_for(@user,  :url => registration_path(@user), :html => {:class => 'form-vertical' }) do |f| %>
	  <%= f.error_notification %>
	  <%= f.input :email, :required => true, :placeholder => "Enter email address..."  %>
	  <%= f.button :submit, 'Sign up' %>
	
	<% end %>

</aside>

<aside id="linkcat-2" class="widget widget_links"><h3 class="widget-title">Links</h3>
	<ul class='xoxo blogroll'>
<li><%= link_to 'Rails Guide', 'http://guides.rubyonrails.org/'%>
<li><%= link_to 'Family Site', 'http://www.denenberg.net'%></li>
	</ul>
</aside>
</div>
				</div>
			</div>
		</div>
	</div>